# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efb14c5803614665a78ba13770d8d86e5642c7e970d8c6ae31562ecd6cefa90107cc6687d63025f804fe214b6f864414714d3e7343497f2ec8902d4088d583a3

test:
  secret_key_base: a76fe6a3e2615877070d457c410b7ae2ac7390ee474725c2ed72601bb4a1915663b7dd27221cfa1e9489043a2c7d3bbdf025ce8c8fb1d55febfd4321ee6e15a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
